image: mcr.microsoft.com/powershell:ubuntu-20.04

stages:
  - build
  - auth

build_job:
  stage: build
  script:
    - apt-get update && apt-get install -y git
    - echo "Pipeline is running..."
    - FILE=$(git diff --name-only HEAD^1 HEAD | grep 'deployments/.*\.ps1')
    - if [ -z "$FILE" ]; then echo "No PowerShell files changed in the deployments directory."; exit 0; fi
    - echo "Changed files:"
    - echo "$FILE"
    - for f in $FILE; do pwsh $f; done
  rules:
    - changes:
        - deployments/**/*

variables:
  AZURE_CLIENT_ID: "<client-id>"
  AZURE_TENANT_ID: "<tenant-id>"

auth_job:
  stage: auth
  id_tokens:
    GITLAB_OIDC_TOKEN:
      aud: https://gitlab.com
  script:
    - az login --service-principal -u $AZURE_CLIENT_ID -t $AZURE_TENANT_ID --federated-token $GITLAB_OIDC_TOKEN
    - az account show
