image: mcr.microsoft.com/powershell:ubuntu-20.04

stages:
  - build

build_job:
  stage: build
  script:
    - apt-get update && apt-get install -y git
    - echo "Pipeline is running..."
    - FILE=$(git diff --name-only HEAD^1 HEAD | grep 'deployments/.*\.ps1')
    - if [ -z "$FILE" ]; then echo "No PowerShell files changed in the deployments directory."; exit 0; fi
    - echo "Changed files:"
    - echo "$FILE"
    - for f in $FILE; do pwsh $f; done

