variables:
  AZURE_CLIENT_ID: ""
  AZURE_TENANT_ID: ""

image:
  name: mcr.microsoft.com/powershell:ubuntu-20.04

stages:
  - check_changes
  - authenticate_and_run

check_changes:
  stage: check_changes
  script:
    - apt-get update
    - apt-get install -y git
    - echo "Checking for git file changes..."
    - FILE=$(git diff --name-only HEAD^1 HEAD | grep 'deployments/.*\.ps1')
    - if [ -z "$FILE" ]; then echo "No PowerShell files changed in Git."; exit 0; fi
    - echo "Changed files:"
    - echo "$FILE"
    - echo $FILE > changed_files.txt
  artifacts:
    paths:
      - changed_files.txt

auth_and_run:
  stage: authenticate_and_run
  dependencies:
    - check_changes
  before_script:
    - apt-get update
    - apt-get install -y curl apt-transport-https gnupg2 lsb-release software-properties-common
    - curl -sL https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
    - echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/azure-cli.list
    - apt-get update
    - apt-get install -y azure-cli
    - curl https://packages.microsoft.com/config/ubuntu/20.04/prod.list | tee /etc/apt/sources.list.d/microsoft-prod.list
    - apt-get update
    - apt-get install -y powershell

  id_tokens:
    GITLAB_OIDC_TOKEN:
      aud: https://gitlab.com

  script:
    - FILE=$(cat changed_files.txt)
    - echo "Authenticating with Azure..."
    - az login --service-principal -u $AZURE_CLIENT_ID -t $AZURE_TENANT_ID --federated-token $GITLAB_OIDC_TOKEN
    - if [ $? -ne 0 ]; then echo "Authentication failed"; exit 1; fi
    - echo "Getting Microsoft Graph API token..."
    - TOKEN=$(az account get-access-token --resource https://graph.microsoft.com --query accessToken -o tsv)
    - echo "Running PowerShell script..."
    - pwsh $FILE -GraphToken $TOKEN
