image: ruby:3.1

stages:
  - deploy

before_script:
  - apt-get update
  - apt-get install -y wget apt-transport-https software-properties-common

  - wget -q "https://packages.microsoft.com/config/debian/11/packages-microsoft-prod.deb"
  - dpkg -i packages-microsoft-prod.deb

  - apt-get update

  #Install pwsh
  - apt-get install -y powershell

deploy_script:
  stage: deploy
  script:
    - echo "Pipeline is running..."
    - |
      FILE=$(git diff --name-only HEAD^1 HEAD | grep 'deployments/.*\.ps1')
      if [ -n "$FILE" ]; then
        pwsh $FILE
      else
        echo "No PowerShell script found to run."
      fi
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      changes:
        - deployments/*.ps1

